### PR TITLE
Added the ability to set the local path from Commandline And Updated README file

### PR DESCRIPTION
**Pull request by hyyan**
I have been using this tool for a while now with build tools like PHING , and I found that the ability to set the local path from command line is essential , and preferred over config file.

I hope the PR will be accepted  , Thanks :)

### CODE REVIEW

**Comment by dg** [comment]
What's you use case? Where is `deployment.ini` placed?

**Comment by hyyan** [comment]
@dg the `deployment.ini ` is still  used to set the ftp cred and other stuff , but the PR add the new cli option `-local=<PATH>` in order to set the `local` folder path .

Where this might be useful ? 
 take a look at this project which used this tool to add the ftp-sync step to a build workflow 
https://github.com/hyyan/gwp/blob/master/build/modules/ftp-sync/ftp-sync.xml#L43

the project just call the tool to deploy the auto generated folder `./dist/deploy` using predefined 
options : 

* ftp-sync.executable
* ftp-sync.deployFile
* ftp-sync.dryrun

[here is where it is defined ](https://github.com/hyyan/gwp/blob/master/build/build.properties#L52)

Now that is all OK but the user stills need to define the path `/dist/deploy' in its `deployment` file which looks like a hard coded option.

With this PR , other apps can set this path automatically like this : 

`deployment deployment.ini -local="./dist/deploy" --test`
`deployment deployment.ini -local="./dist/deploy" --generate`

Hope I explained this well

**Comment by dg** [comment]
What about `./dist/deploy && deployment deployment.ini --test` ?

**Comment by hyyan** [comment]
@dg the solution is OK , if the deployment tool is installed globally , but in my case I am using composer to intsall the tool into `bin/deployment` and the deploy folder is on the `dist/deployment`

**Comment by dg** [comment]
Do you have one `deployment.ini` for more projects or one `deployment.ini` per project?

**Comment by hyyan** [comment]
one file per project

**Comment by hyyan** [comment]
@on file pre project for every environment , for example `deploy-staging` , `deploy-production`

**Comment by dg** [comment]
When `local` in `deployment.ini` is relative path, it is relative to current path (maybe better idea is to compute it relative to the directory where `deployment.ini` is placed, but such change can be big BC break). So solution is to change directory before tool is called. 

You can call tool from a different directory, i.e via `cd ./dist/deploy && ../vendor/bin/deployment deployment.ini --test` etc.

**Comment by hyyan** [comment]
@dg I will try to execute such command with PHING and provide the results here later

**Comment by dg** [comment]
I tried to make 'local' relative to folder, where is 'deployment.ini' placed https://github.com/dg/ftp-deployment/commit/c8fbd37411010f4f1be1f92934ae76759581aea3, but I am really not sure, whether it is not huge BC break…

**Comment by hyyan** [comment]
@dg I have tried to execute the deploy command the way you suggested  , but this is not really possible (it just two complicated) with build tool like PHING or even Ant , I can change to one dir and then execute the deploy command from there with one step .

@dg I am not really sure how changing the `local` path to be relative to current config file might help in this , what we want here is to be able to set the local path from command line directly. keeping the same way this tool understand the local path.

**Comment by dg** [comment]
Maybe I do not understand you. Why you can't have `local` in ini file, when you have one ini per project?

**Comment by hyyan** [comment]
@dg  I have on `ini` file for every environment for example : 

* deploy-staging.ini (more than staging server could be defined) 
* deploy-production.ini (more than production server could be defined (Network site for example)) 
* deploy-testing.ini (more than testing server could be defined) 

now hard coding the local path for every environment in every file , is not ideal , although it is OK

adding such a cli option will allow projects like mine which uses build tool like PHING or Ant to automate the generation of local path cause it might differs according to current environment. instead of letting the user add the local path manually for every one. so he/she want need to add anything expect the server cred.

**Comment by dg** [comment]
@hyyan Sorry, but I really do not understand what you want. I'll close it and feel free to reopen if it still matters.

**Pull request closed without merging**
