### PR TITLE
reduce I/O and deployment time by ~48%

### PR DESCRIPTION
**Pull request by Gamesh**
is_readable in my opinion is not needed as we should presume we will be deploying from a readable sources.
the realpath() there is not necessary, and removing it will save us a lot of I/O.
profiled it with blackfire, an opencart was deployed by 48% faster, reducing the deployment time by 53 seconds, just by making these two changes.
https://blackfire.io/profiles/compare/5c8d40e2-2b72-423f-967a-918c7e7e9c29/graph

### CODE REVIEW

**Comment by dg** [comment]
I am not sure whether realpath is required or not, but we can try it in master ;)
Thanks

**Comment by Gamesh** [comment]
@dg just a side question, why do you use md5 checksum to compare file changes ? wouldn't it be cheaper and faster just to check file modification time with filemtime() ?

**Comment by dg** [comment]
For example, if you run synchronization on multiple computers, filemtime may be different but contents is the same.

**Comment by Gamesh** [comment]
aah yes, i see, thanks, didn't consider that

**Pull request merged**
