### PR TITLE
Change ftp_chmod to ftp_site

### PR DESCRIPTION
**Pull request by chinloyal**
This allows the permissions of the remote folder to be changed from deployment.ini file.

- bug fix
- BC break? no

### CODE REVIEW

**Comment by dg** [comment]
Why it ftp_site better than ftp_chmod?

**Comment by chinloyal** [comment]
I realized when I was using this tool with ftp_chmod and tried to set or even change file permissions or directory permissions from the deployment.ini file it would not work. For example, uncommenting those values below and changing them would result in an error on deployment.

```
; default permissions for new files
filePermissions = 0777

; default permissions for new directories
dirPermissions = 0777
```
I'm not sure if it works for you, or maybe it works on the server you tested on. I am using SmarterAsp's ftp server.

**Comment by dg** [comment]
Can you try this a0b523d0a74b14b25d564a66301d7733815415c7?

**Comment by chinloyal** [comment]
Thank you I will.

**Pull request closed without merging**
